title: YES Kushtia
email: contact@yeskushtia.com
phone: "+880 1XX-XXXXXXX"
address: Kushtia, Bangladesh
footer_text: "© YES Kushtia. Built with ❤️ by Ataur Rahman."
social:
  - title: facebook
    url: "https://www.facebook.com/profile.php?id=100091803572081"
  - title: linkedin
    url: "https://www.linkedin.com/in/ataur-rahman-p-eng-pmp-3b91a460/"
